src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EgioDigital\CMSBundle\Entity\ArticleLike;
use App\Entity\Company;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"})
 * @Vich\Uploadable
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"approved_projects_read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max="50")
     * @Groups({"approved_projects_read"})
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max="50")
     * @Groups({"approved_projects_read"})
     */
    private $lastName;

   /**
    * @ORM\Column(type="string", length=255, nullable=true)
    * @Assert\Length(min=9, max=9)
    */
   private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     * @Groups({"approved_projects_read"})
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8, max="100")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var File|null
     * @Assert\Image(
     *      mimeTypes={"image/jpeg", "image/png"},
     *    maxSize="3M"
     * )
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="avatar")
     */
    private $imageFile;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Expression(
    *     "this.getProfile() in ['admin', 'startuper', 'investor', 'bearer-of-an-associative-project']",
    * )
    */
   private $profile;

   /**
    * @ORM\ManyToOne(targetEntity="App\Entity\Role", inversedBy="users")
    * @ORM\JoinColumn(nullable=false)
    * @Groups({"approved_projects_read"})
    */
   private $role;

   /**
    * @ORM\Column(type="datetime", nullable=true)
    */
   private $lastLogin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateToken;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBanned;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime()
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Project", mappedBy="author")
     */
    private $projects;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ApprovedProject", mappedBy="author", orphanRemoval=true)
     */
    private $approvedProjects;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Faq", mappedBy="author")
     */
    private $faqs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="author")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="EgioDigital\CMSBundle\Entity\ArticleLike", mappedBy="user",cascade={"persist"})
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MailSended", mappedBy="user")
     */
    private $mailSendeds;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RequestDocumentation", mappedBy="user")
     */
    private $requestDocumentations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProjectLike", mappedBy="user")
     */
    private $projectLikes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MessageResponse", mappedBy="user")
     */
    private $messageResponses;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $socialReason;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Company", mappedBy="user")
     */
    private $companies;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompanyComment", mappedBy="author")
     */
    private $companyComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompanyCommentResponse", mappedBy="user")
     */
    private $companyCommentResponses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompanyLike", mappedBy="user")
     */
    private $companyLikes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="users")
     */
    private $city;

   /**
    * User constructor.
    * @throws \Exception
    */
    public function __construct()
    {
        $this->createdAt = new \DateTime('now');
        $this->projects = new ArrayCollection();
        $this->approvedProjects = new ArrayCollection();
        $this->faqs = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->mailSendeds = new ArrayCollection();
        $this->requestDocumentations = new ArrayCollection();
        $this->projectLikes = new ArrayCollection();
        $this->messageResponses = new ArrayCollection();
        $this->companies = new ArrayCollection();
        $this->companyComments = new ArrayCollection();
        $this->companyCommentResponse = new ArrayCollection();
    }

   /**
    * @ORM\PrePersist()
    * @throws \Exception
    */
    public function initializeOnPrePersist(): void
    {
        $this->setIsBanned(false);
        $this->setIsDeleted(false);
        $dateTimeNow = new \DateTime('now');
        $this->setCreatedAt($dateTimeNow);
    }

    public function file_existes($avatar) {
        return file_exists(substr($avatar, 1));
    }

   /**
    * @ORM\PreUpdate
    * @throws \Exception
    */
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new \DateTime('now');
        $this->setUpdatedAt($dateTimeNow);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->firstName . " " . $this->lastName;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

   public function getPhone(): ?string
   {
      return $this->phone;
   }

   public function setPhone(string $phone): self
   {
      $this->phone = $phone;

      return $this;
   }

    public function __toString(): ?string
    {
        return (string)$this->email;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getBirthday()
    {
        return $this->birthday;
    }

    public function setBirthday($birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return  File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return User
     * @throws \Exception
     */
    public function setImageFile($imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getDateToken(): ?\DateTimeInterface
    {
        return $this->dateToken;
    }

    public function setDateToken(?\DateTimeInterface $dateToken): self
    {
        $this->dateToken = $dateToken;

        return $this;
    }

    public function getIsBanned(): ?bool
    {
        return $this->isBanned;
    }

    public function setIsBanned(bool $isBanned): self
    {
        $this->isBanned = $isBanned;

        return $this;
    }

templates/startuper/dashboard/_actus.html.twig
{% trans_default_domain 'project' %}
<div class="b-decouvrir">
    <img src="{{ asset('assets/img/business-woman.png') }}" alt="Discover">
    <div class="discover-content">
        <h3>{% trans %}Benefit from personalized support for your projects{% endtrans %}</h3>
        <a class="btn btn-bg-red btn-h40 btn-w25" href="{{ path('services', { actor: 'startupers'}) }}">
            {% trans %}Discover{% endtrans %}
        </a>
    </div>
</div>

{% if articles|length > 0 %}
    <div class="b-actus-card">
        <h3>{% trans %}News{% endtrans %}</h3>
        <div class="row">
            {% for article in articles %}
                {% include '@CMS/front/article/_card.html.twig' %}
            {% endfor %}
        </div>
    </div>
    <div class="all-actus">
        <div class="text-center">
            <a href="{{ path('cmsbundle_article_list') }}" class="btn btn-bg-red btn-h40 btn-w25">
                {% trans %}See all news{% endtrans %}
            </a>
        </div>
    </div>
{% endif %}

templates/startuper/dashboard/_menu.html.twig
{% trans_default_domain 'project' %}

<div id="accordion" class="accordion">
    {% if app.user.projects|length > 0 %}
        <div class="card">
            <div class="card-header" id="headingOne">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                        aria-expanded="{% if project %}true{% else %}false{% endif %}" aria-controls="collapseOne">
                    <i class="icon-archive"></i>
                    <h4>{% trans %}Projects{% endtrans %}</h4>
                    <i class="icon-right-chevron"></i>
                </button>
            </div>

            <div id="collapseOne" class="collapse{% if project%} show{% endif %}" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <ul class="list-project">
                        {% for proj in projects %}
                            {% set class = "" %}
                            {% if project and proj.id == project.id %}
                                {% set class = "active" %}
                            {% endif %}
                            <li class="{{ class }}">
                                <a href="{{ path('startuper_project_dashboard_show', {id: proj.id, slug: proj.slug}) }}">
                                    {{ proj.name }}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="{{ path('startuper_project_create') }}">
                                {% trans %}Create project{% endtrans %}
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
    {% if app.user.companies|length > 0 %}
        <div class="card">
            <div class="card-header" id="headingTwo">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseTwo"
                        aria-expanded="{% if company %}true{% else %}false{% endif %}" aria-controls="collapseTwo">
                    <i class="icon-archive"></i>
                    <h4>{% trans %}Companies{% endtrans %}</h4>
                    <i class="icon-right-chevron"></i>
                </button>
            </div>

            <div id="collapseTwo" class="collapse {% if company %}show{% endif %}" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                    <ul class="list-project">
                        {% for comp in companies %}
                            {% set class = "" %}
                            {% if company and comp.id == company.id %}
                                {% set class = "active" %}
                            {% endif %}
                            <li class="{{ class }}">
                                <a href="{{ path('startuper_company_dashboard_show', {id: comp.id, slug: comp.slug}) }}">
                                    {{ comp.name }}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="{{ path('startuper_company_create') }}">
                                {% trans %}Create Company{% endtrans %}
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
{#    <div class="card">#}
{#        <div class="card-header" id="headingThree">#}
{#            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">#}
{#                <i class="icon-settings"></i>#}
{#                <h4>{% trans %}Documents & Tools{% endtrans %}</h4>#}
{#                <i class="icon-right-chevron"></i>#}
{#            </button>#}
{#        </div>#}
{#        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">#}
{#            <div class="card-body">#}
{#                <ul>#}
{#                    <li><a href="{{ path('global_document', {type: 'tools'}) }}">{% trans %}In the headlines{% endtrans %}</a></li>#}
{#                    <li><a href="{{ path('global_document', {type: 'document-public'}) }}">{% trans %}Public documents{% endtrans %}</a></li>#}
{#                    <li><a href="{{ path('global_document', {type: 'auto-production'}) }}">{% trans %}Auto-productions{% endtrans %}</a></li>#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

    {% if app.user.messages|length > 0 %}
        <div class="card">
            <div class="card-header" id="headingThree">
                <a href="{{ path('investor_messages') }}" class="btn btn-link">
                    <i class="icon-open-email"></i>
                    <h4>{% trans %}Messages{% endtrans %}</h4>
                    {#<i class="icon-right-chevron"></i>#}
                </a>
            </div>
        </div>
    {% endif %}
</div>

templates/startuper/dashboard/content-company.html.twig
{% trans_default_domain 'company' %}
<div class="b-statistiques">
    <h3>{% trans %}Statistics{% endtrans %}</h3>.
{#    <div class="row b-cards">#}
{#        <div class="col-md-6 progress-dash">#}
{#            {{ company.amountCollected|number_format(0, ',', ' ') }} MAD#}
{#            <br>#}
{#            {% if approvedCompany %}#}
{#                {{ approvedCompany.fundingObjective|number_format(0, ',', ' ') }} MAD#}
{#            {% else %}#}
{#                {{ company.fundingObjective|number_format(0, ',', ' ') }} MAD#}
{#            {% endif %}#}
{#            {% if approvedCompany and approvedCompany.fundingObjective != company.fundingObjective %}#}
{#                <br>#}
{#                <span class="text-danger">#}
{#                    <small>#}
{#                        {{ company.fundingObjective|number_format(0, ',', ' ') }} MAD#}
{#                        {{ 'Is your new funding goal in draft mode while the administrator validates it'|trans }}#}
{#                    </small>#}
{#                </span>#}
{#            {% endif %}#}
{#            {% if approvedCompany %}#}
{#                {% set percent = approvedCompany.percentageOfContribution %}#}
{#            {% else %}#}
{#                {% set percent = company.percentageOfContribution %}#}
{#            {% endif %}#}
{#            <div class="progress-content mt-3">#}
{#                <div class="progress">#}
{#                    <div class="progress-bar" style="width: {{ percent }};" role="progressbar" aria-valuenow="50" aria-valuemin="50" aria-valuemax="100"></div>#}
{#                </div>#}
{#                <div class="percentage">{{ percent}}</div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <div class="row b-cards">
        <div class="col-md-3">
            <div class="card-icon"><i class="icon-visites"></i></div>
            <div class="card-text">
                <h5>{{ company.views|default(0) }}</h5>
                <h4>{% trans %}Visits{% endtrans %}</h4>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card-icon"><i class="icon-like"></i></div>
            <div class="card-text">
                <h5>
                    {{ company.likes|length }}
                </h5>
                <h4>{% trans %}Likes{% endtrans %}</h4>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card-icon"><i class="icon-secteur"></i></div>
            <div class="card-text">
                <h5>
                    {{ company.contributors|length }}
                </h5>
                <h4>
                    {% if company.contributors|length > 1 %}
                        {% trans %}Contributors{% endtrans %}
                    {% else %}
                        {% trans %}Contributor{% endtrans %}
                    {% endif %}
                </h4>
            </div>
        </div>
    </div>
</div>

templates/startuper/dashboard/message.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block stylesheets %}
    <style>
        .active {
            background-color: #bfd9ff;
            color: white !important;
        }
    </style>
{% endblock %}

{% trans_default_domain 'project' %}

{% block body %}

    <div class="dashboard-project">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 sidebar-project-menu">
                {% include 'startuper/dashboard/_menu.html.twig' %}
            </div>
            <div class="col-lg-9 sidebar-project-content">
{#                {% include 'startuper/dashboard/_head.html.twig' %}#}

                <div class="block-messagerie">
                    <div class="c-messagerie-heading">
                        <a href="{{ path('startuper_project_messages', { id: project.id, slug: project.slug}) }}" class="more">
                            {% trans %}Messages{% endtrans %}
                        </a>
                        <h5 class="h-project">{% trans %}Projet{% endtrans %}</h5>
                        <h1 class="h-title">
                            {{ message.project.name }}
                        </h1>
                         <h3>{{ message.object }}</h3>
                    </div>

                    <div class="msg-content">
                        <div class="row justify-content-start">
                            <div class="col-md-7 b-info-author ur-msg">
                                <div class="avatar-heading">
                                    {% set author = message.author %}
                                    <div class="avatar-user">
                                        <img src="{{ vich_uploader_asset(author, 'imageFile') }}" alt="" class="img-responsive">
                                    </div>
                                    <div class="avatar-details">
                                        <div class="c-author-name">{{ message.author.fullName }} </div>
                                        <div class="c-dtate-time">
                                            <ul>
                                                <li><i class="icon-calendar"></i> {{ message.createdAt|date('d/m/Y') }}</li>
                                                <li><i class="icon-clock"></i> {{ message.createdAt|date('H:i:s') }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="response-msg">
                                    {{ message.content }}
                                </div>
                            </div>
                        </div>
                     </div>

                    <div class="b-messageries-line">
                        {% for response in message.responses %}
                            {% set author = response.user.fullName  %}
                            {% set color = 'light'  %}
                            {% set class = 'justify-content-start'  %}
                            {% if app.user == response.user %}
                                {% set author = 'You'|trans %}
                                {% set color = 'response'  %}
                                {% set class = 'justify-content-end'  %}
                            {% endif %}
                            <div class="msg-content">
                                <div class="row {{ class }}">
                                    <div class="col-md-7">
{#                                        <div class="alert alert-{{ color }}">#}
                                        <div class="massage-field {{ color }}">
                                            
                                            {% set user = response.user %}
                                            <div class="avatar-user">
                                                <img src="{{ vich_uploader_asset(user, 'imageFile') }}" alt="" class="img-responsive">
                                            </div>
                                            <div class="avatar-details">
                                                <div class="c-author-name">{{ author }}</div>
                                                <div class="c-dtate-time">
                                                    <ul>
                                                        <li><i class="icon-calendar"></i> {{ response.createdAt|date('d/m/Y') }}</li>
                                                        <li><i class="icon-clock"></i> {{ response.createdAt|date('H:i:s') }}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="response-msg">{{ response.content }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="form-add-new-msg">
                        <div class="row">
                            <div class="col-md-12">
                            {{ form_start(form) }}
                            <div class="field-message">
                                {{ form_widget(form) }}
                            </div>
                            <div class="g-recaptcha"
                                 data-sitekey="{{ recaptcha_site_key }}"
                                 data-callback="onSubmitMessage"
                                 data-size="invisible">
                            </div>
                            <button type="submit" class="btn btn-bg-red btn-h50 btn-w15">
                                {% trans %}Reply{% endtrans %}
                            </button>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>

            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script>
        function onSubmitMessage(token) {
            $('#message-response-form').submit();
        }
    </script>
{% endblock %}

templates/startuper/dashboard/messages.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block stylesheets %}
    <style>
        .active {
            background-color: #bfd9ff;
            color: white !important;
        }
    </style>
{% endblock %}

{% trans_default_domain 'project' %}

{% block body %}

    <div class="dashboard-project">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 sidebar-project-menu">
                {% include 'startuper/dashboard/_menu.html.twig' %}
            </div>
            <div class="col-lg-9 sidebar-project-content">
{#                {% include 'startuper/dashboard/_head.html.twig' %}#}
                {% include 'partials/_notice.html.twig' %}

                <div class="project-table">
                    <h3 class="">Messages</h3>

                    <div class="table-head">
                        <div class="row table-row">
                            <div class="col-md-3 project">
                                <strong>
                                    {% trans %}Project{% endtrans %}
                                </strong>
                            </div>
                            <div class="col-md-4 object">
                                <strong>
                                    {% trans %}Object{% endtrans %}
                                </strong>
                            </div>
                            <div class="col-md-2 author">
                                <strong>
                                    {% trans %}Author{% endtrans %}
                                </strong>
                            </div>
                            <div class="col-md-2 date">
                                <strong>
                                    {% trans %}Date{% endtrans %}
                                </strong>
                            </div>
                        </div>
                    </div>

                    <div class="table-body">
                        {% for message in pagination %}
                            {% set class = "" %}
                            {% if message.seen == 0 %}
                                {% set class = 'active' %}
                            {% elseif message.isSeen(app.user) == 1 %}
                                {% set class = "active" %}
                            {% endif %}
                            <a href="{{ path('startuper_project_reply_message',
                            {id: project.id, slug:project.slug, idMessage: message.id}) }}">
                                <div class="row table-row {{ class }}">
                                    <div class="col-md-3 project">
                                        {{ message.project.name }}
                                    </div>
                                    {% set countResponse = message.responses|length %}
                                    <div class="col-md-4 object">
                                        {{ message.object }}
                                        ({{ countResponse }} Message{% if countResponse > 1 %}s{% endif %})
                                    </div>
                                    <div class="col-md-2 author">
                                        {{ message.author.fullName }}
                                    </div>
                                    <div class="col-md-2 date">
                                        {{ message.createdAt|date('d/m/Y - H:i:s') }}
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>

                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
    </div>
{% endblock %}

templates/startuper/dashboard/response.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block stylesheets %}
    <style>
        .active {
            background-color: #bfd9ff;
            color: white !important;
        }
    </style>
{% endblock %}

{% trans_default_domain 'project' %}

{% block body %}

    <div class="dashboard-project">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 sidebar-project-menu">
                {% include 'startuper/dashboard/_menu.html.twig' %}
            </div>
            <div class="col-lg-9 sidebar-project-content">
                {% include 'startuper/dashboard/_head.html.twig' %}

                <h3 class="mt-5 mb-3">{{ question.question }}</h3>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button type="submit" class="btn btn-bg-red btn-h50 btn-w15">Reply</button>
                {{ form_end(form) }}

            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
    </div>
{% endblock %}